fint:
  metamodel-url: http://localhost:8082
  gateway-url: http://fint-customer-object-gateway.flais-io.svc.cluster.local:8080
  idp-url: https://idp.felleskomponent.no/nidp/oauth/nam/token
spring:
  webflux:
    base-path: /test-runner
