fint:
  metamodel-url: http://fint-core-consumer-metamodel.fint-core.svc.cluster.local:8080
  gateway-url: http://fint-customer-objects-gateway.flais-io.svc.cluster.local:8080
  idp-url: https://idp.felleskomponent.no/nidp/oauth/nam/token
spring:
  webflux:
    base-path: /test-runner
